### ISSUE TITLE
icalBuddy returns "No Calendars" on new Warp terminal 

### ISSUE THREAD

**Issue by ivishalgandhi** [ali-rantakari/icalBuddy#37]
Getting an error message on Warp terminal. https://www.warp.dev/
error: No calendars.
tried brew uninstall and install ; not able to make it work. 
Pleae advise.

**Comment by timhradil** [comment]
This is because Warp requests calendar access, but not reminders access. When I run icalbuddy on Terminal it requests both calendar and reminder access. I am not sure why Warp does not request reminder access and why icalBuddy needs it, but I did find a work around. You can create a forceReminderAccess.scpt script like this:
```
tell application "Reminders"
        return reminders
end tell
```
And run it using `osascript forceReminderAcceess.scpt`. Then just accept all the access prompts and confirm Warp has access to reminders in System Settings.

**Comment by ivishalgandhi** [comment]
@timhradil it works now. Thank you :)

**Comment by Soben** [comment]
Just encountered this on Ghostty as well. No real reason why it should require Reminders, but glad this solved it.
